### ISSUE TITLE
Up/Down navigation for simulating windows-alt-tab using touchpad

### ISSUE THREAD

**Issue by KAGEYAM4** [H3rmt/hyprswitch#129]
```
bind = $mod, $key, exec, hyprswitch gui --mod-key $mod --key $key --max-switch-offset 9
```

Dosen't support Up/Down key and only Right/Left.

Having up/down would enable [Alt-tab-switcher for touchpad like windows](https://github.com/iberianpig/fusuma/wiki/3-fingers-Alt-Tab-Switcher(Windows-Style))

Also, it would be make navigation using touchpad more natural, as currently if there are three window in a workspace, two vertically and one beside, navigating using hyprswitch will go through all three of them, wheras it would be more natural if a user press right twice it only navigates in horizontal direction.

https://github.com/user-attachments/assets/e9ae9955-cc5d-463d-996a-2e5f3242d31a

This is the config i was using for fusuma -->
```
swipe:
  4:
    begin:
      command: "ydotool key 125:1 15:1 15:0 125:0"
    right:
      update:
        command: "ydotool key 106:1 106:0"
    left:
      update:
        command: "ydotool key 105:1 105:0"
    up:
      update:
        command: "ydotool key 103:1 103:0"
    down:
      update:
        command: "ydotool key 108:1 108:0"
    end:
        command: "ydotool key 28:1 28:0"
```
