### ISSUE TITLE
Feature: display in gui only current workspace

### ISSUE THREAD

**Issue by klephron** [H3rmt/hyprswitch#179]
In the current release, there is an option `--filter-current-workspace` to disable the selection of clients that are not part of the current workspace. However, they are still visible in the GUI. It would be convenient to completely hide the filtered-out workspaces with clients from the GUI view and to position these clients at the beginning of the workspace list.

Also it makes sense with these CSS options, described in Wiki:

```css
.workspace {
    /* remove workspace name */
    font-size: 0;
    font-weight: lighter;

    background-color: transparent;
    border: unset;
}

.monitor {
    background-color: transparent;
    border: unset;
}
```

Which gives this output:

```sh
hyprswitch gui --mod-key alt --key tab --close mod-key-release --reverse-key=mod=shift --sort-recent -w && hyprswitch dispatch
```

![Image](https://github.com/user-attachments/assets/2d5818f8-061d-4b23-a155-d7096af4c636)

Here clients are present on workspaces 1, 3, 4, 6.
